version: '3.8'

services:
  travel-recommender-api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: travel-recommender-api-container
    ports:
      - "8002:8002"
    volumes:
      - travel-recommender-models:/app/models
      - travel-recommender-logs:/app/logs
    restart: unless-stopped
    environment:
      - PYTHONUNBUFFERED=1
      - PYTHONDONTWRITEBYTECODE=1
    healthcheck:
      test: ["CMD", "python", "-c", "import requests; requests.get('http://localhost:8002/health')"]
      interval: 30s
      timeout: 30s
      retries: 3
      start_period: 40s
    networks:
      - travel-recommender-network

volumes:
  travel-recommender-models:
    driver: local
  travel-recommender-logs:
    driver: local

networks:
  travel-recommender-network:
    driver: bridge
